Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
viewer = napari.view_image(data.astronaut(), rgb=True)
points = np.array([[100, 100], [200, 200], [300, 100]])
point_properties = {
    'good_point': np.array([True, True, False]),
    'confidence': np.array([0.99, 0.8, 0.2]),
}

points_layer = viewer.add_points(
    points,
    properties=point_properties,
    edge_color='good_point',
    edge_color_cycle=['magenta', 'green'],
    edge_width=0.5,
)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 8[0m
[1;32m      2[0m points [38;5;241m=[39m np[38;5;241m.[39marray([[[38;5;241m100[39m, [38;5;241m100[39m], [[38;5;241m200[39m, [38;5;241m200[39m], [[38;5;241m300[39m, [38;5;241m100[39m]])
[1;32m      3[0m point_properties [38;5;241m=[39m {
[1;32m      4[0m     [38;5;124m'[39m[38;5;124mgood_point[39m[38;5;124m'[39m: np[38;5;241m.[39marray([[38;5;28;01mTrue[39;00m, [38;5;28;01mTrue[39;00m, [38;5;28;01mFalse[39;00m]),
[1;32m      5[0m     [38;5;124m'[39m[38;5;124mconfidence[39m[38;5;124m'[39m: np[38;5;241m.[39marray([[38;5;241m0.99[39m, [38;5;241m0.8[39m, [38;5;241m0.2[39m]),
[1;32m      6[0m }
[0;32m----> 8[0m points_layer [38;5;241m=[39m [43mviewer[49m[38;5;241;43m.[39;49m[43madd_points[49m[43m([49m
[1;32m      9[0m [43m    [49m[43mpoints[49m[43m,[49m
[1;32m     10[0m [43m    [49m[43mproperties[49m[38;5;241;43m=[39;49m[43mpoint_properties[49m[43m,[49m
[1;32m     11[0m [43m    [49m[43medge_color[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mgood_point[39;49m[38;5;124;43m'[39;49m[43m,[49m
[1;32m     12[0m [43m    [49m[43medge_color_cycle[49m[38;5;241;43m=[39;49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mmagenta[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mgreen[39;49m[38;5;124;43m'[39;49m[43m][49m[43m,[49m
[1;32m     13[0m [43m    [49m[43medge_width[49m[38;5;241;43m=[39;49m[38;5;241;43m0.5[39;49m[43m,[49m
[1;32m     14[0m [43m)[49m

[0;31mTypeError[0m: add_points() got an unexpected keyword argument 'edge_color'

